#!/bin/bash
# A simple script to run smith in a dockerized environment (and to ease the transition from Vagrant)
# Copyright (c) 2022 SIL International (http://www.sil.org)'
# Released under the MIT License (http://en.wikipedia.org/wiki/MIT_License)
# maintained by Nicolas Spalinger


OS=$(uname -sm)
COMPOSE="$HOME/repos/anvil/docker-compose.yml"

case $1 in
        "validate" | "check" | "config")
                echo "Validating configuration"
                docker compose -f "$COMPOSE" config
                ;;
        "up" | "start")
                echo "Getting image, spinning up the container and provisionning"
                docker compose -f "$COMPOSE" -p smith build --pull
                docker compose -f "$COMPOSE" up -d --remove-orphans 
                ;;
        "provision")
                echo "No need to use provision any longer, use up instead"
                ;;
        "status" | "ps")
                echo "Showing container status"
                docker compose -f "$COMPOSE" ps
                ;;
        "ssh" | "enter" | "exec" | "run")
                echo "Entering the container in interactive mode (type exit to get back)"
                if [[ "$OS" == *"MSYS_NT-10"* ]]; 
                        then winpty docker compose -f "$COMPOSE" run smith 
                        else docker compose -f "$COMPOSE" run smith 
                fi
                ;;
        "when" | "time")
                echo -e "ID              Creation date                   Status"
                docker container ls --format '{{.ID}}\t{{.CreatedAt}}\t{{.State}}\t{{.Status}}'
                ;;
        "stop" | "halt" | "destroy" | "down")
                echo "Stopping and removing the container"
                docker compose -f "$COMPOSE" down
                ;;
        "clean" | "prune" | "purge")
                echo "Purging stale images / containers and the whole build cache"
                docker stop "$(docker ps -aq)"
                docker rm "$(docker ps -aq)"
                docker rmi -f smith
                docker system prune -a
                ;;
        *)
                echo "Anvil: 🦾 🏗  helper for running a dockerized smith"
                echo "Config file: $COMPOSE"
                echo "Usage: expected a parameter (alias) like:"
                echo "  anvil up (start)"
                echo "  anvil ssh (enter) (exec) (run)"
                echo "  anvil status (ps)"
                echo "  anvil stop (halt) (destroy) (down)"
                ;;
esac
