#!/bin/bash
# A backup script for repos inside WSL

BACKUPDIR="/mnt/c/backups/WSL-repositories-backups"

mkdir -p $BACKUPDIR

echo "Creating a backup of repositories in WSL to $BACKUPDIR"

tar cpf $BACKUPDIR/wsl-repositories-backup-"$(date +%m-%d-%Y-%Hh%Mm)".tar ~/repos/wstechfonts --totals --checkpoint=.3000 

echo "Done"
