---
services:
  smith:
    restart: unless-stopped
    image: "ghcr.io/silnrsi/smith:latest"
    # Uncomment the following 2 lines if you'd like to build a local image from the smith repository (and comment out the image: line above)
    #build:
    #  context: $HOME/repos/smith/
    stdin_open: true
    tty: true
    init: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 30000
        hard: 60000
    volumes:
      # adjust to your own local font project folder structure
      # (syntax details on https://docs.docker.com/compose/compose-file/#volumes)
      - type: bind
        source: $HOME/repos/wstechfonts
        target: /smith
      # the volume mounting below is to sync the timezone with the host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: smith
    hostname: smith
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 8gb
          # the following lines only work on Windows10/11 and Ubuntu when you have an nVidia GPU with the latest nVidia driver installed
          # uncomment these 3 lines for GPU acceleration but only for Windows10/11 and Ubuntu, macOS already does its own GPU acceleration.
        # devices:
        #    - driver: nvidia
        #      capabilities: [gpu]

        # uncomment the following lines for GPU acceleration with Intel and AMD Radeon but only for Windows10/11 and Ubuntu with the corresponding drivers installed, macOS already does its own GPU acceleration.
        # this is still experimental and not always guaranteed to work 
        # devices:
        #   - "dev/kfd:/dev/kfd"
        #   - "dev/dri:/dev/dri"
        # group_add:
        #   - video
        #   - render
