---
version: "3.9"
services:
  smith:
    restart: unless-stopped
    image: "ghcr.io/silnrsi/smith:latest"
    # uncomment the following 2 lines if you'd like to build a local image from the smith repository (and comment out the image: line above)
    #build:
    #  context: $HOME/repos/smith/
    stdin_open: true
    tty: true
    volumes:
      # adjust to your own local font project folder structure
      # (syntax details on https://docs.docker.com/compose/compose-file/#volumes)
      - type: bind
        source: $HOME/repos/wstechfonts
        target: /smith
    container_name: smith
    hostname: smith-focal
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 12gb
          # the lines below (under devices:) only work on Ubuntu and Windows10/11 when you have an nVidia GPU and you have installed the latest nVidia driver
          # comment out or remove these 3 lines for macOS
          devices:
            - driver: nvidia
              capabilities: [gpu]

