---
version: "3.9"
services:
  smith:
    restart: unless-stopped
    image: "ghcr.io/silnrsi/smith:latest"
    #build:
    #  context: $HOME/repos/smith/
    stdin_open: true
    tty: true
    volumes:
      # adjust to your own local font project folder structure
      # source on your host OS : target inside the container
      # (syntax details on https://docs.docker.com/compose/compose-file/#volumes)
      - type: bind
        source: $HOME/repos/wstechfonts
        target: /smith
    container_name: smith
    hostname: smith-focal
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 12gb
